version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    ports:
      - "8000:80"
      - "8001:443" 
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Port=5432;Database=frog;User Id=username;Password=password;

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: